### ISSUE TITLE
Why solder jumpers?

### ISSUE THREAD

**Issue by hitchclimber** [raeedcho/chocofi-temper#23]
Hi, sorry this is not a real issue, but there was no tab to start a discussion. I'm not an electrical engineer and new to soldering and was wondering why do we have to solder the jumpers? Is that some standard practice in that case?
In the example pictures it doesn't look like soldering them creates any connection.

**Comment by raeedcho** [comment]
Soldering them does indeed create a connection--if you look at the before picture, there's a gap between the jumper pads that gets bridged when you solder them. In general solder jumpers allow for modification of the circuit for specific purposes after the PCB has been printed, creating connections where there are not wired connections in the copper traces of the PCB. In this case, the jumpers need to be soldered to complete the connections correctly for the microcontroller to the rest of the board PCB.

Design-wise, there's one main problem the jumpers solve in the temper: I wanted to use a reversible PCB so that I could use the same design for both halves. There are other solutions to this problem:

- put separate holes for the MCU depending on which half it's on (see the chocofi for an example of this solution)
- solder the microcontroller upside down on one of the halves (I don't think I've ever seen this, but it's a possibility I think)
- give up the reversibility and just make separate designs for each half (doubles the price of PCBs)

I felt like the jumpers were the more elegant solution, at the price of being slightly more finicky.

**Comment by hitchclimber** [comment]
Thanks a lot! And great work by the way!
